### Add a bike
POST http://localhost:3000/admin/addBike
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6MSwiaWF0IjoxNzM3ODIyMjMzLCJleHAiOjE3Mzc5MDg2MzN9.9eUrJdFHRtDatz5GR378KmejVRbjpk4t2qHUI1f58Yc

{
    "type": "Cross Country",
    "image": "https://www.canyon.com/dw/image/v2/BCML_PRD/on/demandware.static/-/Sites-canyon-master/default/dw43edfae3/images/full/full_2023_/2023/full_2023_3443_lux-trail-cf-8_M138_P01_P5.jpg?sw=501&sh=282&sm=fit&sfrm=png&q=90&bgcolor=F2F2F2",
    "name": "Lux Trail CF 8",
    "size": "L"
}

### Get all bikes
GET http://localhost:3000/bikes/allBikes

### Add a new customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "johnsmith@example.com",
    "password": "ilovebikes123"
}

### Login an existing user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "johnsmith@example.com",
    "password": "ilovebikes123"
}

### Add a new customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "bobsmith@example.com",
    "password": "ilovebikes123"
}

### Rent bike 1
PUT http://localhost:3000/customer/rentBike/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3ODIyNTMxLCJleHAiOjE3Mzc5MDg5MzF9.NOan9r0kXWQZUJ3NBvg8kgGcnAW4MvBAczjbJTenHpg

### Add a new customer
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "example3@example.com",
    "password": "3"
}